version: '3.7'

volumes:
  dev-db:

services:
  mysql: # A MySQL instance for the game server to use
    image: mysql:5.7
    restart: always
    environment:
      # Configured the database credentials
      # Refer to https://hub.docker.com/_/mysql for more info.
      MYSQL_DATABASE: dodiannet
      MYSQL_USER: dodian
      MYSQL_PASSWORD: dodian_local_development_123
      MYSQL_ALLOW_EMPTY_PASSWORD: 'false'
    ports:
      - '3306:3306'
    volumes:
      # Where our data will be persisted
      - dev-db:/var/lib/mysql
      # Enable the below SQL file mappings if you want to initialize the database with data.
      # Do note that these files (the way they are done in this example) need to be in the same directory as this file.
      # You can find them in the "database"-directory of the game-server module
      # !! Everything depends on the mandatory_tables.sql, unless you take care of the database another way
      #- ./mandatory_tables.sql:/docker-entrypoint-initdb.d/1_mandatory_game_tables.sql
      #- ./dodian_default_data.sql:/docker-entrypoint-initdb.d/2_dodian_default_data.sql
      #- ./convenient_data.sql:/docker-entrypoint-initdb.d/3_convenient_game_data.sql
      #- ./dummy_development_data.sql:/docker-entrypoint-initdb/4_dummy_game_data.sql